# Generated by Django 2.1.7 on 2020-07-21 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200721_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Read_Num',
            new_name='ReadNum',
        ),
    ]
