# Generated by Django 2.1.7 on 2020-07-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appname',
            name='app_href',
            field=models.CharField(default='#', max_length=20),
        ),
    ]
